baseurl: ""
url: "http://teambabylon.github.io"
excerpt_separator: "<!--more-->"

permalink: pretty

theme: jekyll-theme-slate

title: Team Babylon
description: A collective blog for a collection of nerds.
authors: Xander Thompson, Brett Settle, John Thorpe, Nick Prendergast
paginate: 5
plugins: [jekyll-paginate]
version: 1.0.0
