theme: jekyll-theme-slate
name: Team Babylon
description: A collective blog for a collection of nerds.
author: Xander Thompson, Brett Settle, John Thorpe, Nick Prendergast
category_dir: /
permalink: pretty
